### ISSUE TITLE
Can't find starting point when performance is very low

### ISSUE THREAD

**Issue by EleeStalker** [fruendlab/esdt#2]
I have a dataset that looks like this:
```
[[ 0.025  0.35  20.   ]
 [ 0.1    0.5   20.   ]
 [ 0.15   0.4   20.   ]
 [ 0.175  0.45  20.   ]
 [ 0.2    0.65  20.   ]
 [ 0.25   0.35  20.   ]
 [ 0.3    0.5   20.   ]
 [ 0.35   0.5   20.   ]]
```
and the fitted psychometric function has `NaN` in the first two parameters. This seems to be related to searching the starting point of the optimization.

**Comment by igordertigor** [comment]
This should be fixed with pull request #1
